# Generated by Django 3.2.7 on 2021-09-04 10:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address_city', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('PM', 'PM'), ('F&B', 'F&B')], max_length=64)),
                ('desc_department', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_problem', models.CharField(choices=[('Desktops/laptops', 'Desktops/laptops'), ('Pherieral devices', 'Pherieral devices'), ('Mobile Devices', 'Mobile Devices'), ('Network Infrastructure', 'Network Infrastructure'), ('Work Schedule', 'Work Schedule'), ('Hiring Process', 'Hiring Process'), ('Employee', 'Employee'), ('Documents', 'Documents'), ('Project realization', 'Project realization'), ('Improvement', 'Improvement'), ('Inspection', 'Inspection'), ('Desktops/laptops', 'Desktops/laptops'), ('Invoices', 'Invoices'), ('Payment', 'Payment'), ('Delegation payment', 'Delegation payment'), ('Orders', 'Orders'), ('Other', 'Other')], max_length=64)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(choices=[('Not Acknowledged', 'Not Acknowledged'), ('Pending ', 'Pending'), ('Pending Requestor Information', 'Pending Requestor Information'), ('Work in Progress', 'Work in Progress'), ('Resolved Successfull', 'Resolved Successfull'), ('Resolved', 'Resolved'), ('Blocked', 'Blocked'), ('Dropped', 'Dropped')], max_length=64)),
                ('status_statement', models.CharField(choices=[('Desktops/laptops', 'Desktops/laptops'), ('Pherieral devices', 'Pherieral devices'), ('Mobile Devices', 'Mobile Devices'), ('Network Infrastructure', 'Network Infrastructure'), ('Work Schedule', 'Work Schedule'), ('Hiring Process', 'Hiring Process'), ('Employee', 'Employee'), ('Documents', 'Documents'), ('Project realization', 'Project realization'), ('Improvement', 'Improvement'), ('Inspection', 'Inspection'), ('Desktops/laptops', 'Desktops/laptops'), ('Invoices', 'Invoices'), ('Payment', 'Payment'), ('Delegation payment', 'Delegation payment'), ('Orders', 'Orders'), ('Other', 'Other')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('priorytet', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'ASAP')], default=1, max_length=64)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolve', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ManyToManyField(to='ticket_app.Correspondence')),
                ('department_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.department')),
                ('problem_problem_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.departmentproblem')),
                ('status', models.OneToOneField(default='Not Acknowledged', on_delete=django.db.models.deletion.CASCADE, to='ticket_app.status')),
                ('user_requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
