# Generated by Django 3.2.7 on 2021-09-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='problem_problem_category',
            new_name='problem_category',
        ),
        migrations.AlterField(
            model_name='department',
            name='name_department',
            field=models.CharField(choices=[('Test', 'Test'), ('IT', 'IT'), ('HR', 'HR'), ('PM', 'PM'), ('F&B', 'F&B')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='ticket_app.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
