# Generated by Django 3.2.7 on 2021-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_auto_20210904_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='correspondence',
            field=models.ManyToManyField(related_name='ticket_correspondence', to='ticket_app.Correspondence'),
        ),
    ]
