# Generated by Django 3.2.7 on 2021-09-04 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_ticket_correspondence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user_requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
