# Generated by Django 3.2.7 on 2021-09-04 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_alter_ticket_user_requestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='correspondence',
        ),
        migrations.AddField(
            model_name='ticket',
            name='correspondence',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='ticket_correspondence', to='ticket_app.correspondence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_resolve',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='problem_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem_category',
            field=models.ManyToManyField(to='ticket_app.DepartmentProblem'),
        ),
    ]
