# Generated by Django 3.2.7 on 2021-09-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_auto_20210904_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='correspondence',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='ticket_correspondence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_correspondence', to='ticket_app.ticket'),
        ),
    ]
