# Generated by Django 3.2.7 on 2021-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_auto_20210904_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_statement',
        ),
        migrations.AlterField(
            model_name='departmentproblem',
            name='category_problem',
            field=models.CharField(choices=[('Desktops/Software', 'Desktops/Software'), ('Pherieral devices', 'Pherieral devices'), ('Mobile Devices', 'Mobile Devices'), ('Network/Infrastructure', 'Network/Infrastructure'), ('Work Schedule', 'Work Schedule'), ('Hiring Process', 'Hiring Process'), ('Employee', 'Employee'), ('Documents', 'Documents'), ('Project realization', 'Project realization'), ('Improvement', 'Improvement'), ('Inspection', 'Inspection'), ('Invoices', 'Invoices'), ('Payment', 'Payment'), ('Delegation payment', 'Delegation payment'), ('Orders', 'Orders'), ('Other', 'Other')], max_length=64),
        ),
    ]
