# Generated by Django 3.2.7 on 2021-09-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Not Acknowledged', 'Not Acknowledged'), ('Pending ', 'Pending'), ('Pending Requestor Information', 'Pending Requestor Information'), ('Work in Progress', 'Work in Progress'), ('Resolved Successfull', 'Resolved Successfull'), ('Resolved', 'Resolved'), ('Blocked', 'Blocked'), ('Dropped', 'Dropped')], default='Not Acknowledged', max_length=64),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
