# Generated by Django 3.2.7 on 2021-09-04 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_auto_20210904_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_assignment',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_department',
            field=models.CharField(max_length=64),
        ),
    ]
