# Generated by Django 3.2.7 on 2021-09-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_alter_departmentproblem_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='problem_category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_problem_category', to='ticket_app.departmentproblem'),
        ),
    ]
