# Generated by Django 3.2.7 on 2021-09-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0012_auto_20210904_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_resolve',
            field=models.DateTimeField(default=None),
        ),
    ]
