# Generated by Django 3.2.7 on 2021-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0014_alter_ticket_date_resolve'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Not Acknowledged', 'Not Acknowledged'), ('Pending ', 'Pending'), ('Pending Requestor Information', 'Pending Requestor Information'), ('Work in Progress', 'Work in Progress'), ('Blocked', 'Blocked'), ('Dropped', 'Dropped'), ('Resolved Successfull', 'Resolved Successfull')], default='Not Acknowledged', max_length=64),
        ),
    ]
