# Generated by Django 3.2.7 on 2021-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0025_alter_ticket_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Acknowledged', 'Not Acknowledged'), ('Pending ', 'Pending'), ('Pending Requestor Information', 'Pending Requestor Information'), ('Work in Progress', 'Work in Progress'), ('Blocked', 'Blocked'), ('Dropped', 'Dropped'), ('Resolved Successfull', 'Resolved Successfull')], default='Not Acknowledged', max_length=64),
        ),
    ]
