# Generated by Django 3.2.7 on 2021-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0028_alter_ticket_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
