# Generated by Django 3.2.7 on 2021-09-07 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0032_alter_ticket_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 7, 10, 11, 54, 363848, tzinfo=utc)),
        ),
    ]
