# Generated by Django 3.2.7 on 2021-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0033_auto_20210907_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
